// Mocks generated by Mockito 5.0.14 from annotations
// in iothub/test/pages/iothub/iothub_main_test.dart.
// Do not manually edit this file.

import 'dart:async' as i4;

import 'package:iothub/src/data_source/auth_repository.dart' as i3;
import 'package:iothub/src/domain/entities/device.dart' as i7;
import 'package:iothub/src/domain/entities/iothub.dart' as i6;
import 'package:iothub/src/domain/entities/measurement.dart' as i8;
import 'package:iothub/src/domain/entities/user.dart' as i2;
import 'package:iothub/src/service/iothub_service.dart' as i5;
import 'package:mockito/mockito.dart' as i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeUser_0 extends i1.Fake implements i2.User {}

/// A class which mocks [FirebaseAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuthRepository extends i1.Mock
    implements i3.FirebaseAuthRepository {
  MockFirebaseAuthRepository() {
    i1.throwOnMissingStub(this);
  }

  @override
  i4.Future<void> init() => (super.noSuchMethod(Invocation.method(#init, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as i4.Future<void>);
  @override
  i4.Future<i2.User> signUp(i2.UserParam? param) =>
      (super.noSuchMethod(Invocation.method(#signUp, [param]),
              returnValue: Future<i2.User>.value(_FakeUser_0()))
          as i4.Future<i2.User>);
  @override
  i4.Future<i2.User> signIn(i2.UserParam? param) =>
      (super.noSuchMethod(Invocation.method(#signIn, [param]),
              returnValue: Future<i2.User>.value(_FakeUser_0()))
          as i4.Future<i2.User>);
  @override
  i4.Future<void> signOut(i2.UserParam? param) =>
      (super.noSuchMethod(Invocation.method(#signOut, [param]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as i4.Future<void>);
  @override
  i4.Future<i2.User> currentUser() =>
      (super.noSuchMethod(Invocation.method(#currentUser, []),
              returnValue: Future<i2.User>.value(_FakeUser_0()))
          as i4.Future<i2.User>);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
}

/// A class which mocks [IOTHubService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIOTHubService extends i1.Mock implements i5.IOTHubService {
  MockIOTHubService() {
    i1.throwOnMissingStub(this);
  }

  @override
  i4.Future<List<i6.IOTHub>> loadAllIOTHubs() =>
      (super.noSuchMethod(Invocation.method(#loadAllIOTHubs, []),
              returnValue: Future<List<i6.IOTHub>>.value(<i6.IOTHub>[]))
          as i4.Future<List<i6.IOTHub>>);
  @override
  i4.Future<List<i7.Device>> loadAllDevices(String? selectedIOTHubID) =>
      (super.noSuchMethod(
              Invocation.method(#loadAllDevices, [selectedIOTHubID]),
              returnValue: Future<List<i7.Device>>.value(<i7.Device>[]))
          as i4.Future<List<i7.Device>>);
  @override
  i4.Future<List<i8.Measurement<dynamic>>> loadLastMeasurement(
          String? iothubId, i7.Device? device) =>
      (super.noSuchMethod(
              Invocation.method(#loadLastMeasurement, [iothubId, device]),
              returnValue: Future<List<i8.Measurement<dynamic>>>.value(
                  <i8.Measurement<dynamic>>[]))
          as i4.Future<List<i8.Measurement<dynamic>>>);
  @override
  i4.Stream<List<i8.Measurement<dynamic>>> deviceAllMeasurementStream(
          String? iothubDocumentId, i7.Device? device) =>
      (super.noSuchMethod(
              Invocation.method(
                  #deviceAllMeasurementStream, [iothubDocumentId, device]),
              returnValue: Stream<List<i8.Measurement<dynamic>>>.empty())
          as i4.Stream<List<i8.Measurement<dynamic>>>);
}
