// Mocks generated by Mockito 5.0.14 from annotations
// in iothub/test/pages/nas/nas_sync_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as i3;
import 'dart:io' as i7;

import 'package:iothub/src/domain/entities/nas_file_item.dart' as i4;
import 'package:iothub/src/domain/value_objects/upload_file_status.dart' as i6;
import 'package:iothub/src/service/interfaces/local_file_system_service.dart'
    as i8;
import 'package:iothub/src/service/interfaces/nas_file_sync_service.dart'
    as i2;
import 'package:iothub/src/service/nas_file_sync_state.dart' as i5;
import 'package:mockito/mockito.dart' as i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [NASFileSyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNASFileSyncService extends i1.Mock
    implements i2.NASFileSyncService {
  MockNASFileSyncService() {
    i1.throwOnMissingStub(this);
  }

  @override
  i3.Future<List<i4.NASFileItem>> retrieveDirectoryItems(
          String? folderPath,
          double? dateFromSeconds,
          double? dateToSeconds,
          i5.FileTypeForSync? fileTypeForSync) =>
      (super.noSuchMethod(
              Invocation.method(#retrieveDirectoryItems, [
                folderPath,
                dateFromSeconds,
                dateToSeconds,
                fileTypeForSync
              ]),
              returnValue:
                  Future<List<i4.NASFileItem>>.value(<i4.NASFileItem>[]))
          as i3.Future<List<i4.NASFileItem>>);
  @override
  i3.Stream<i6.UploadFileStatus> sendFiles(
          List<i7.File>? transferringFileList,
          String? nasFolderPath,
          i5.FileTypeForSync? fileTypeForSync) =>
      (super.noSuchMethod(
              Invocation.method(#sendFiles,
                  [transferringFileList, nasFolderPath, fileTypeForSync]),
              returnValue: Stream<i6.UploadFileStatus>.empty())
          as i3.Stream<i6.UploadFileStatus>);
  @override
  void cancelRequest() =>
      super.noSuchMethod(Invocation.method(#cancelRequest, []),
          returnValueForMissingStub: null);
  @override
  i3.Future<List<String>> listSambaFolders(String? baseFolder) =>
      (super.noSuchMethod(Invocation.method(#listSambaFolders, [baseFolder]),
              returnValue: Future<List<String>>.value(<String>[]))
          as i3.Future<List<String>>);
}

/// A class which mocks [LocalFileSystemService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalFileSystemService extends i1.Mock
    implements i8.LocalFileSystemService {
  MockLocalFileSystemService() {
    i1.throwOnMissingStub(this);
  }

  @override
  i3.Future<List<i7.File>> matchLocalFiles(
          String? localFolderPath,
          bool? recursive,
          i5.FileTypeForSync? fileTypeForSync,
          DateTime? dateFrom,
          DateTime? dateTo,
          List<i4.NASFileItem>? remoteFiles) =>
      (super.noSuchMethod(
              Invocation.method(#matchLocalFiles, [
                localFolderPath,
                recursive,
                fileTypeForSync,
                dateFrom,
                dateTo,
                remoteFiles
              ]),
              returnValue: Future<List<i7.File>>.value(<i7.File>[]))
          as i3.Future<List<i7.File>>);
}
